### ISSUE TITLE
/api/v3/openOrders returning wrong data

### ISSUE THREAD

**Issue by DrRek** [binance/binance-api-postman#102]
As you can see from the attached videos the /api/v3/openOrders returns wrong data during tests with postman.

As you can see in the video I have 3 open orders (both CHZEUR) and the api returns from 0 to 3 results each time I run it.
In the second video I have 1 CHZEUR order and 1 MATICEUR order, also in this case the api returns wrong values.

https://user-images.githubusercontent.com/12783153/119256347-8d14d600-bbc0-11eb-8709-9027fe140413.mp4

https://user-images.githubusercontent.com/12783153/119256411-eed54000-bbc0-11eb-9f7c-1113041e2a7a.mp4

**Comment by ishuen** [comment]
Thanks for the feedback. Will check it with the team, grazie.

**Comment by ishuen** [comment]
Hi. This is due to the incomplete DB cluster synchronisation.
You can either send API request with longer waiting time or subscribe to websocket user data stream and maintain the execution report locally.

**Comment by DrRek** [comment]
Thanks! Is there a suggested wait time to use in order to have an higher chance of getting correct results?

**Comment by 2pd** [comment]
For API related question, please open a topic at dev.binance.vision.
