### ISSUE TITLE
Long/Short Ratio data is not complete

### ISSUE THREAD

**Issue by acuna-public** [binance/binance-api-postman#103]
Seems that Long/Short Ratio API methods don't return all data what it needed, now it's returns only data from Long/Short columns, but it makes no sense, because it's always almost the same:

![One](https://github.com/acuna-public/Binance/blob/main/screens/2021-05-24_183855.png?raw=true)

So only one accurate way is to get exactly ratio graph, which shows the correct data, so if we gets its `longShortRatio` from API and can simply compare it with ratio overage value which is, as for 15m timeframe for example, is _(1.08 + 1.20) / 2 = 1.14_

![One](https://github.com/acuna-public/Binance/blob/main/screens/2021-05-24_184439.png?raw=true)

![One](https://github.com/acuna-public/Binance/blob/main/screens/2021-05-25_220554.png?raw=true)

But the problem is that API methods for this don't returns min and max ratio values for get its overage, I can get it from Futures Trade Data page and hardcode it in my code, but it's depends on timeframe and columns number, so unfortunately it's impossible. It will be great to add the ratio min and max value to the api methods like `topLongShortPositionRatio` results to get its overage value to compare it with ratio value getting from API. Thanks in advance.

**Comment by ishuen** [comment]
Hi. Thanks for your feedback. Unfortunately, your images attached are missing so it's a bit hard to understand your context.
1. Can you clarify which endpoint you are talking about? There are several endpoints returning this attribute name.
2. What is the expected behaviour/ output? Please provide a sample json object as an example.

**Comment by acuna-public** [comment]
Hello, it's `/futures/data/topLongShortPositionRatio` and others
JSON output given in text, it's

![One](https://github.com/acuna-public/TraderBot/blob/main/screens/2021-05-25_220554.png?raw=true)

**Comment by ishuen** [comment]
Hi.
The attachment you shared are not available as last time. Can you try another way to share it? E.g. paste the actual text instead of displaying it in a file.
![image](https://i.imgur.com/leIG3WO.png[/img])

**Comment by acuna-public** [comment]
Oh my, I'm so sorry, I've took the screens from private repo, but I've tested it. So strange. Edit my post for you, please check it.

**Comment by ishuen** [comment]
> But the problem is that API methods for this don't returns min and max ratio values for get its overage, I can get it from Futures Trade Data page and hardcode it in my code, but it's depends on timeframe and columns number, so unfortunately it's impossible. 
What is your expectation about the min and max ratio? How does it different from the min and max value you can extract from an array of the ratios when querying the API with startTime and endTime specified?

**Comment by 2pd** [comment]
this is not postman collection related question.

**Comment by acuna-public** [comment]
@2pd okay, but where I need to write about issues in API, because dev.banance.org is for users questions? Unfortunately seems it's only one way to contact the devs.
