### ISSUE TITLE
Sockets answers empty even when ACCOUNT_UPDATE action is occured

### ISSUE THREAD

**Issue by xgeorgejacksonx** [binance/binance-api-postman#104]
Hello, I'm using non-standart language and communicate with HTTP by plain headers. I'm wanted to get some futures methods info (for example `positionRisk`) via sockets, but gets an empty answer even my balance is changing (I have some futures open orders). I'm sending the following headers to the server:

    GET /ws/L7Awe0UboTNATaoiutuz9lSZg6wRYO1A1PquzoS4SjIg8Cq2lRsabadIQcYlFWI9 HTTP/1.1\r\n
    Host: stream.binance.com\r\n
    Accept: */*\r\n
    Connection: Upgrade\r\n
    Upgrade: WebSocket\r\n
    Pragma: no-cache\r\n
    Sec-WebSocket-Version: 13\r\n
    Sec-WebSocket-Key: 6DLUcxfnOxFAet7PJDrXYg==\r\n
    \r\n
    \r\n

And getting the correct answer headers, but answer body is empty.

    HTTP/1.1 101 Switching Protocols
    Date: Fri, 28 May 2021 14:26:44 GMT
    Connection: upgrade
    Upgrade: websocket
    Sec-WebSocket-Accept: KFe2yYd1Hu9qNmIaaZR56apFrCQ=

I'm tried both of the endpoints to generate listen key (`fapi/v1/listenKey` and `api/v3/userDataStream`) and with testnet too with no luck.

What it can be, because, for example, pairs trade info (`/stream?streams=btcusdt@kline_1m`) working good?

Thanks.

**Comment by 2pd** [comment]
when connection to websocket server, you will send tcp connection, and then upgrade to websocket connection.  You may need to test based on some websocket libraries, that should be easier to understand how websocket works.

Btw please discusss API tech issue at dev.binance.vision. Only postman collection related issue is allowed here.
