### ISSUE TITLE
"Signature for this request is not valid."

### ISSUE THREAD

**Issue by noobaldrin** [binance/binance-api-postman#105]
Hello, I'm developing an application for my own use. I'm new to using API's, I'm using Postman to check outputs/responses without adding them to my application yet.

When I query for Deposit and Withdrawal history I'm getting this as response.

```
{
    "code": -1022,
    "msg": "Signature for this request is not valid."
}
```
Other queries work using my API and Secret keys.

Things I've tried:
Restricted my API to work only on my IP address
Enabled all possible API restrictions
Cleared the signature on my Postman environment

Please HALP. Thanks in advance

**Comment by ishuen** [comment]
Hi.
There are some possible reasons, please check them accordingly:
1. uncheck all the parameters that does not have input.
2. check if the correct secret key is provided
3. check if the signature has something in the environment setting file (If it is empty, the pre-request script may goes wrong.)
Hope these steps resolve the issue.

**Comment by noobaldrin** [comment]
Hmm I see now. the coin parameter is not mandatory. I left timestamp and signature checked and the rest are disabled.

Thanks a lot!

**Comment by samgermain** [comment]
I'm getting the same issue when trying to do "Margin Order New Order (Trade)" I clear the signature, but every time I send a request again, the signature field gets filled.

I can send other requests, and can even make margin requests through third party python libraries

[Here's a screenshot of my postman settings](https://imgur.com/OsMymhq)

**Comment by 2pd** [comment]
double quotes are not required. @samgermain

**Comment by samgermain** [comment]
@2pd Thanks, it looks like I can make a trade now, but I can't use any leverage, I have **27.37831693** in my cross margin account, but if I try to make an order for anything higher than that ( [here's a screenshot for an order](https://imgur.com/Hn1n4NN) that try's to order 30 XRP, priced at ~**0.90** right now) then I get an insufficient funds error

**Comment by samgermain** [comment]
I just realized that borrowing is a seperate request

**Comment by theforceofhabit** [comment]
Hello, 
I have a similar issue with the "Binance spot API / Wallet / All Coins' Information (USER_DATA)" request. I did not change any of the parameters just filled in my key and secret in the environment variables. I get the response "Signature for this request is not valid." I don't understand what I'm doing wrong. 
Any help will be much apreciated
My params and headers in the pictures below.
![image](https://user-images.githubusercontent.com/60292099/124021210-911beb00-d9eb-11eb-8b80-789571d5da41.png)
![image](https://user-images.githubusercontent.com/60292099/124021262-a1cc6100-d9eb-11eb-9b82-06aa67027899.png)

**Comment by 2pd** [comment]
- did you provide the correct api key and secrect?
- did you set them in the postman environment file as required.

**Comment by theforceofhabit** [comment]
Hey 2pd, thanks for the reply! Yes I did both those things, that's why I'm confused, I tried also a new API key and secret but it did not change a thing, I still got the same response.
