### ISSUE TITLE
Error: You are not authorized to execute this request

### ISSUE THREAD

**Issue by smontico** [binance/binance-api-postman#106]
I'm executing the following endpoint: /sapi/v1/capital/deposit/hisrec?coin=BTC&status&startTime&endTime&addressTag=&timestamp={{timestamp}}

in Postman and i get "401 Unauthorized" with the message "You are not authorized to execute this request".
I can make others queries so the parameters seems to be right.

Any help?

**Comment by ishuen** [comment]
Hi.
Can you check if you attached signature as one of the query parameter?

**Comment by smontico** [comment]
The method I'm using doesn't seems to need it:

https://binance-docs.github.io/apidocs/spot/en/#deposit-history-supporting-network-user_data

**Comment by ishuen** [comment]
If you see “USER_DATA” at the end of the API name, it means both API-Key (in header) and signature (in query parameter) are required.
Please refer to the document here. https://binance-docs.github.io/apidocs/spot/en/#endpoint-security-type
