### ISSUE TITLE
Signature error in Futures

### ISSUE THREAD

**Issue by franrc** [binance/binance-api-postman#115]
Hi!

I'm trying to test the binance Futures API but I always get:

{
    "code": -1022,
    "msg": "Signature for this request is not valid."
}

I have this restrictions for the API

<img width="942" alt="Captura de pantalla 2021-07-29 a las 6 13 40" src="https://user-images.githubusercontent.com/16647610/127430452-bfe11751-0ff5-4253-86f3-48858ee388d3.png">

I have the correct API key and Secret key on my postman environment, but I'm getting the error with all requests which the signature is required.

<img width="1011" alt="Captura de pantalla 2021-07-29 a las 6 15 15" src="https://user-images.githubusercontent.com/16647610/127430569-99a496f9-2e02-4843-a2a5-119dbda2a23a.png">

What I'm doing wrong?

Thanks in advance.

**Comment by tantialex** [comment]
This may be caused due to incorrect API credentials. Please confirm that you are using the correct environment and the correct environment variables.

![image](https://user-images.githubusercontent.com/17701918/127653725-f53bf1a4-24c6-4d96-9274-faf6566edb94.png)

**Comment by 2pd** [comment]
close the ticket due to no response.
