### ISSUE TITLE
Signature for this request is not valid

### ISSUE THREAD

**Issue by IbrahimSerhat** [binance/binance-api-postman#133]
`{
    "code": -1022,
    "msg": "Signature for this request is not valid."
}`

i set everything as well like binance api key and secret.
i check all of it.
X-MBX-APIKEY is true.

i can get every result as well at market and accout tabs like Account Trade List but when i try under of Order tab like All Orders i got an signature error.

**Comment by ishuen** [comment]
Hi.
Could you double check if all optional parameters without values are all unchecked?
If so, can you extract the raw query string for that specific request? It will be helpful for the investigation.

**Comment by IbrahimSerhat** [comment]
@ishuen thanks, i checked 'All Orders' for an example and i was not type symbol. i filled symbol by BTCUSDT and it works.
