### ISSUE TITLE
GET /fapi/v2/accountveGET /fapi/v2/positionRiskGET /fapi/v2/accountveGET /fapi/v2/positionRisk

### ISSUE THREAD

**Issue by Semaerdem3536** [binance/binance-api-postman#139]
-

**Comment by Semaerdem3536** [comment]
GET /fapi/v2/accountveGET /fapi/v2/positionRisk

**Comment by Semaerdem3536** [comment]
GET /fapi/v2/accountveGET /fapi/v2/positionRisk

**Comment by Semaerdem3536** [comment]
GET /fapi/v2/accountveGET /fapi/v2/positionRisk

**Comment by ishuen** [comment]
Please provide the proper and informative context when creating an issue, thanks.
