### ISSUE TITLE
Any endpoint for creating new sell/buy market order?

### ISSUE THREAD

**Issue by adnanaman** [binance/binance-api-postman#148]
I couldn't find any market based orders endpoints... closest i could think is below

{{url}}/api/v3/order?symbol=BTCBUSD&side=BUY&type=MARKET&timeInForce=GTC&quantity=0.00020&price=1&timestamp={{timestamp}}&signature={{signature}}

but when i run it i get below

{
    "code": -1022,
    "msg": "Signature for this request is not valid."
}

so what am i missing ???

**Comment by 2pd** [comment]
please try to save and then click send again.
Btw MARKET order doesn't need `timeInForce` .

**Comment by adnanaman** [comment]
what about price? parameter looks like that is more redundant?

**Comment by tantialex** [comment]
The mandatory parameters for a MARKET order are: `symbol, side, type, timestamp and (quantity or quoteOrderQty)`.

Consult the documentation if you encounter questions regarding the API.

> 
> Type | Additional mandatory parameters
> -- | --
> **MARKET** | quantity or quoteOrderQty
> 

https://binance-docs.github.io/apidocs/spot/en/#new-order-trade

**Comment by adnanaman** [comment]
Hi

First of all, thank you for your response, i certainly consulted API documentation for this particular endpoint and tried only with mandatory parameters. 

{{url}}/api/v3/order?symbol=BTCBUSD&side=SELL&type=MARKET&quantity=0.00020&timestamp={{timestamp}}&signature={{signature}}

I tried above with environment Binance Spot API and yes I believe my API key and secret are configured correctly as I m able to run other endpoints without any issue. 

Though my API permissions are set for API Reading and Enable Spot & Margin Trading

correct if i should enable any other API restriction for this particular one... 

Also... i am holding 0.00020 BTC at the moment to test this... which i wanted to SELL through MARKET... in BUSD... 

appreciate your help

**Comment by 2pd** [comment]
Please setup spot testnet account and test again. https://testnet.binance.vision/

Then open the postman console to check the raw log, that maybe helpful for debug.
