### ISSUE TITLE
New endpoint for Pay: GET /sapi/v1/pay/transactions to support user query Pay trade history

### ISSUE THREAD

**Issue by drafdecode** [binance/binance-api-postman#152]
Change Log 2021-11-19
GET  {{url}}/sapi/v1/pay/transactions?timestamp={{timestamp}}&signature={{signature}}

Not Found Fields: [
  Pay ID ?
  recipient ?
  sender ? 
  orderId ?
  note ?
]

Example Response:

{
    "code": "000000",
    "message": "success",
    "data": [
        {
            "orderType": "C2C",
            "transactionId": "C_P_XXXXX",
            "transactionTime": 1633941540055,
            "amount": "236.6",
            "currency": "USDT",
            "fundsDetail": [
                {
                    "currency": "USDT",
                    "amount": "236.6"
                }
            ]
        }
    ],
    "success": true
}

**Comment by 2pd** [comment]
what do you mean? where did you find those fields? not in the API document.

**Comment by drafdecode** [comment]
I can't find sender or recipient information.

**Comment by drafdecode** [comment]
> what do you mean? where did you find those fields? not in the API document.

I can't find sender or recipient information.

**Comment by tantialex** [comment]
The endpoint is not intended to return the mentioned fields. 

Consult the documentation for the response schema

https://binance-docs.github.io/apidocs/spot/en/#get-pay-trade-history-user_data
