### ISSUE TITLE
test get response 404?

### ISSUE THREAD

**Issue by youngqiankun** [binance/binance-api-postman#154]
![image](https://user-images.githubusercontent.com/6263774/144983287-c63ef878-3e6d-4ada-bd6f-843e4e35d3c8.png)
![image](https://user-images.githubusercontent.com/6263774/144983334-4c61abeb-edf9-4594-a915-823e16114836.png)

**Comment by frzsombor** [comment]
@youngqiankun I had the same problem, but what is more important is that you just exposed both your keys with the two images, so change them immediately

**Comment by frzsombor** [comment]
@youngqiankun I had the same problem, but what is more important is that you just exposed both your keys with the two images, so change them immediately ( @tantialex @2pd @ishuen )

**Comment by tantialex** [comment]
The Spot Testnet only supports `/api/*` endpoints. `/sapi/*` endpoints are not supported and will return a `404` response.

**Comment by liho00** [comment]
> The Spot Testnet only supports `/api/*` endpoints. `/sapi/*` endpoints are not supported and will return a `404` response.

pls reopen,

```
curl --location --request GET 'https://testnet.binance.vision/sapi/v1/system/status' \
--header 'Content-Type: application/json'
```
this endpoint is under /sapi/*, however 404 returned...
