### ISSUE TITLE
Postman not setting BInance environment variables

### ISSUE THREAD

**Issue by djp9192** [binance/binance-api-postman#180]
Hi, i've used Postman for Binance for some time successfully, but not for a while ... and now all requests which require an API key fail:
    "code": -2008,
    "msg": "Invalid Api-Key ID." 
In the code say for {{url}}/sapi/v1/capital/config/getall?timestamp={{timestamp}}&signature={{signature}} the environment variable is not being set properly::
    myHeaders.append("X-MBX-APIKEY", "api-key");
And when i hover on  the environment variable in the Header section of the API call, you can see that the current value is not set.

But in the Environment, the variable binance-api-key has the correct initial value and current value set.

p.s. i've reinstalled POSTMAN for Desktop, and i've deleted and reimported the Binance SPOT collection and the Environment.

Any ideas?

**Comment by chairz-2** [comment]
From the Postman UI, navigate to `Environment` and make sure that the `Initial Value` and `Current Value` are set with your API Key correctly. Try to create a new API Key if it fails again.

**Comment by djp9192** [comment]
Yes, as mentioned, in the Environment, the variable binance-api-key has the correct initial value and current value set.

I did try many different sets of API keys, before i realized that that wasn't helping, since the API parms and header weren't using the refreshed environment variable values.

**Comment by chairz-2** [comment]
https://github.com/postmanlabs/postman-app-support/issues/6001#issuecomment-1164603270

There is an issue thread for this on postman. Try and see if this fixes your problem.

**Comment by djp9192** [comment]
Thanks, but it doesn't help.   I've tried all the suggestions already, I've signed out & in, uninstalled and reinstalled postman, deleted and reimported the collection and environment, and the bug is still there.

**Comment by 2pd** [comment]
Go to the postman menu:
View -> Show Postman Console
Then you will see the raw logo of each request. You should be able to see what exactly API key was sent in the request header.

**Comment by djp9192** [comment]
Yes, thanks i've checked that before.    From the console it also shows that no value is being set for X-MBX-APIKEY (from the environment variable which does have a correct value):
Request Headers
Content-Type: application/json
X-MBX-APIKEY: api-key

**Comment by 2pd** [comment]
![image](https://user-images.githubusercontent.com/365354/189274185-0f5aa4df-8236-4b23-abb8-9cbd95fb034d.png)

Please check the environment file and also the header in each request. Make sure you have the SAME settings as in the screenshot.

The header setting comes from the post collection. Maybe it worths to download the collection and import it again.

**Comment by djp9192** [comment]
Yes thanks, the header is exactly as per the screen shot, and the environment variable is set for that variable.
![header](https://user-images.githubusercontent.com/83822019/189294918-648fec85-6a94-40b2-acf1-864b8971b9b9.png)

But when you hover you see the header variable doesn't contain the expected value.

I've deleted and reimported the collection and environment several times, and reinstalled postman, but same problem ever time.

**Comment by 2pd** [comment]
that's weird. Maybe you can try setup the environment file again?
Or maybe reinstall the postman. Not sure why the `binance-api-key` is not set.

**Comment by 2pd** [comment]
Please open new issue if you still has any difficult.
