### ISSUE TITLE
Cannot get exercised orders from eapi/v1/order 

### ISSUE THREAD

**Issue by yury-dubinin** [binance/binance-api-postman#186]
Hey guys,

when I am trying to get exercised order(s) from `/eapi/v1/order?symbol=ETH-221007-1600-C` it returns an error:
`Param orderIds or clientOrderIds must be sent, but both were empty/null`

<img width="756" alt="image" src="https://user-images.githubusercontent.com/62520712/195143335-b71302c1-ef4e-449b-a019-1fe31afdcbdd.png">

If I try to use `orderId(s)` param it returns error:
`Signature for this request is not valid.`

<img width="447" alt="image" src="https://user-images.githubusercontent.com/62520712/195144123-8f5887e1-2da2-4ceb-b959-70659df8fee5.png">

**Comment by yury-dubinin** [comment]
looks like endpoint name should be `/exerciseRecord`. I guess, you can update it.

**Comment by 2pd** [comment]
Thanks for feedback, we will update the collection.

**Comment by 2pd** [comment]
https://github.com/binance/binance-api-postman/pull/187
