### ISSUE TITLE
Deposit Issue Binance api

### ISSUE THREAD

**Issue by awais33** [binance/binance-api-postman#191]
I read the document for the deposit. I followed the steps but I am stuck in one step

step 1: I get the deposit address for deposit crypto i.e USDT through the binance api. because i am using binance apis to create my exchange. If my users want to deposit crypto using binance api.

step 2: I have usdt address, then I login to my kucoin account in my mobile app and then withdraw the 20 USDT to the address created in 1st step

step 3: In this step, How binance knows whether it receives 20 USDT or not, any webhook or any other method please help me,
Please help me
Thanks

**Comment by boydtech761** [comment]
Message https://t.me/boydtech on telegram he’s the best on account recovering

**Comment by aisling-2** [comment]
Hello,
sorry for late reply. For the mentioned situation, I believe you can use this [GET /sapi/v1/capital/deposit/hisrec](https://binance-docs.github.io/apidocs/spot/en/#deposit-history-supporting-network-user_data) endpoint - named "Deposit History (supporting network) (User Data)" in Postman - to get the Deposit History.

User data Websocket Stream is not support, but if you want to develop your own project, you can refer to https://binance-docs.github.io/apidocs/spot/en/#payload-balance-update to receive deposits or withdrawals from the account information.
