### ISSUE TITLE
Order/NewOrder price should be marked as disabled

### ISSUE THREAD

**Issue by christian-teza** [binance/binance-api-postman#192]
NewOrder -> price query is not marked as disabled [here](https://github.com/binance/binance-api-postman/blob/master/collections/binance_perpetual_future_api_v1.postman_collection.json#L1797).

But if you send orderType=MARKET with price you get a response
```
Parameter 'price' sent when not required
```

**Comment by 2pd** [comment]
Unfortunately it's not so flexibility to set parameters visibility.  The price is required for many other order type, like `LIMIT`. So I would suggest users to toggle the parameters for their needs.  This placing order has much more parameters than others and may need a little bit more time to learn.
