### ISSUE TITLE
Fetch deposit history - Missing from documentation

### ISSUE THREAD

**Issue by roadbridgeaward** [binance/binance-api-postman#194]
The [offset] input parameter to the endpoint [/sapi/v1/capital/deposit/hisrec] / “Fetch deposit history.”  is not documented and has no description anywhere - kindly please document it or at least add a simple description.

**Comment by aisling-2** [comment]
Hello,

the `offset` is not specific to Binance API, but it's a common parameter in general API pagination system that's used to go through different batches of items. 
This should be a good link for you to understand more https://rapidapi.com/guides/api-pagination#offset-paging.

Therefore, it's not documented and I believe there's no need to be.
