### ISSUE TITLE
How to obtain broker test API key and secret?

### ISSUE THREAD

**Issue by EnkhAmar** [binance/binance-api-postman#200]
Hello,

I've been using the Binace Postman collection from this repository and it has been very helpful for my development work. However, I'm currently facing an issue related to obtaining the broker test API key and secret.

After going through the available methods in the collection, I couldn't find any specific instructions on how to retrieve the broker test API key and secret. I would greatly appreciate it if someone could guide me on how to obtain these credentials.

I have checked the documentation and explored the code, but I couldn't find any relevant information. It would be helpful if the repository's maintainers or anyone with knowledge about the process could provide some guidance.

Any additional details or code snippets related to retrieving the broker test API key and secret would be highly appreciated. I believe that updating the documentation or providing an example in the codebase would benefit other users as well.

Thank you in advance for your assistance!

Best regards,
Enkh-Amar

**Comment by 2pd** [comment]
Sorry for the late response.

The broker program has been rebanded to Link program: https://www.binance.com/en/link, and the API is for entities that join this program.  Please feel free to view it's details from above link and contact the team via Email [link@binance.com](mailto:link@binance.com) if you are interested.

thanks
