### ISSUE TITLE
Staking Endpoints: WBETH related API

### ISSUE THREAD

**Issue by weitude** [binance/binance-api-postman#211]
Can you support WBETH related API?
https://binance-docs.github.io/apidocs/spot/en/#get-wbeth-rate-history-user_data 

![image](https://github.com/binance/binance-api-postman/assets/98746868/a1f9f641-6d67-4d21-9c67-c7b163fed775)

**Comment by alplabin** [comment]
These endpoints have been added in the latest release: https://github.com/binance/binance-api-postman/releases/tag/v1.16.0
