### ISSUE TITLE
"api/v3/avgPrice" how can i get 60 days avg price?

### ISSUE THREAD

**Issue by yaoliangjun** [binance/binance-api-postman#222]
"api/v3/avgPrice" how can i get 60 days avg price? thanks! default is mins : 5
![1718768473263](https://github.com/binance/binance-api-postman/assets/7575968/fb19c596-8546-4e81-a149-77b935913081)

**Comment by alplabin** [comment]
Unfortunately, this API only returns the current average price for a symbol: https://developers.binance.com/docs/binance-spot-api-docs/rest-api#current-average-price.

If you're looking for historical price data on a symbol, I would recommend using the endpoints for [klines](https://developers.binance.com/docs/binance-spot-api-docs/rest-api#klinecandlestick-data) or [aggregate trades](https://developers.binance.com/docs/binance-spot-api-docs/rest-api#compressedaggregate-trades-list).

You can also explore historical data at: https://data.binance.vision/
