### ISSUE TITLE
How can I request for testnet balance

### ISSUE THREAD

**Issue by eljasuhonen** [binance/binance-api-postman#224]
Hi,
want to test trading and wondering where / how I can request for test balance for my testnet account: test user 1721742565888227952 ?

**Comment by alplabin** [comment]
Please take a look at the following website to learn how to use the testnet: https://testnet.binance.vision/
If you’d like to check your testnet account balance, you can use this API: https://developers.binance.com/docs/binance-spot-api-docs/rest-api#account-information-user_data"
