### ISSUE TITLE
Timestamp for this request is outside of the recvWindow.

### ISSUE THREAD

**Issue by thunguyen1012** [binance/binance-api-postman#234]
Look likes Binance API has changed. it is returning error "Timestamp for this request is outside of the recvWindow."

Do you have any idea on this?

**Comment by draghtnight** [comment]
Duplicate of #

**Comment by thunguyen1012** [comment]
I would like to close this one. You can find the solution on https://dev.binance.vision/t/error-timestamp-for-this-request-is-outside-of-the-recvwindow/1357
