### ISSUE TITLE
Strategy orders

### ISSUE THREAD

**Issue by nyckyta** [binance/binance-api-postman#68]
Hey, I am looking for an API scheme for strategy orders in Binance (OCO, OTOCO). Unfortunately nor API docs nor this repo does not contain such information. Is it possible to add it?

**Comment by 2pd** [comment]
OCO is support for spot market, https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#new-oco-trade

**Comment by nyckyta** [comment]
Are there any plans to support it for futures market?

**Comment by 2pd** [comment]
sorry we don't have ETA on that yet.
