### ISSUE TITLE
"-1022 Signature for this request is not valid." error on creation of new order

### ISSUE THREAD

**Issue by muratozenc** [binance/binance-api-postman#78]
Hi,

When I try to create new order from Postman I got "-1022 Signature for this request is not valid." error. I checked the [address](https://github.com/binance/binance-spot-api-docs/blob/master/errors.md#-1022-invalid_signature) for the error but it seems there is no problem about my post. My raw URL is below, changed my secret with XXXX

https://api.binance.com/api/v3/order?side=SELL&type=LIMIT&timeInForce=GTC&quantity=0.01&price=9000&newClientOrderId=my_order_id_1&timestamp=1613681901685&signature=XXXX&symbol=FRONTBUSD

help please.

**Comment by 2pd** [comment]
1. Have a try on other symbol, like `BNBUSDT`
2. move `symbol=FRONTBUSD` to the front of `timestamp`

Please let us know if that works

**Comment by muratozenc** [comment]
None of them worked.

**Comment by 2pd** [comment]
Please don't paste api key or secret.

**Comment by 2pd** [comment]
are you sure the api key and secret is correct? 

Also move the `symbol=BNBUSDT` to the top.

**Comment by muratozenc** [comment]
Hi,

Yes I am sure key and secret values are correct. I can use other api endpoints, can access my spot wallet etc.

I moved it to the top but nothing changes.

<img width="1380" alt="image" src="https://user-images.githubusercontent.com/39806668/108686242-2ff87e00-7506-11eb-97f0-a7fefd1691d5.png">

**Comment by 2pd** [comment]
leave
- timestamp
- signature

as the last 2 parameters, NOTHING underneath.  
`signature` is the last parameter.

**Comment by muratozenc** [comment]
Yes you are right, sorry for the replacements. It seems its working now, but I do not understand what the new error means?

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/39806668/108687775-2c65f680-7508-11eb-81ce-5b521a328a20.png">

**Comment by muratozenc** [comment]
I found the answer, thanks @2pd :)
