### ISSUE TITLE
{     "code": -1002,     "msg": "You are not authorized to execute this request." }

### ISSUE THREAD

**Issue by shanAliKhos** [binance/binance-api-postman#86]
{{url}}/sapi/v1/capital/config/getall?timestamp=1616338278&signature={{signature}}

**Comment by shanAliKhos** [comment]
how to get authorized

**Comment by 2pd** [comment]
No need to manually set the `timestamp`, leave it as:

`{{url}}/sapi/v1/capital/config/getall?timestamp={{timestamp}}&signature={{signature}}`

**Comment by shanAliKhos** [comment]
If I leave it as it is . It gives exception timestamp is required

**Comment by 2pd** [comment]
![image](https://user-images.githubusercontent.com/365354/112778748-e664fb00-9090-11eb-865d-b058b3bf29e7.png)
