### ISSUE TITLE
Testnet. New Order. 'Signature for this request is not valid' if env variable is used

### ISSUE THREAD

**Issue by ppapazov** [binance/binance-api-postman#93]
if ‘symbol’ is used from environment variables, it responds with error:

![var](https://user-images.githubusercontent.com/35167756/116518830-6a511380-a8d9-11eb-8d83-b9463fd1edee.png)

works fine if ‘symbol’ is hardcoded in the Params:
![novar](https://user-images.githubusercontent.com/35167756/116518848-6e7d3100-a8d9-11eb-99fc-c4da88554a2f.png)

**Comment by 2pd** [comment]
symbol is not pre defined in the variables,  you can set it by yourself in the script.

**Comment by milansoliya4210** [comment]
@ppapazov same problem with me,  how you solved it??
