### ISSUE TITLE
url issues

### ISSUE THREAD

**Issue by RT-Tap** [binance/binance-api-postman#99]
Hi I'm not sure if this is intended and I'm in the wrong here but it looks like the request urls seem to be outdated using /v1/ rather than /v3/ and I assume v1 is depreciated because I was never able to get it to work.
Also different collections of requests seem to have a d, s or f in front of api leading to things like /dapi/, /sapi/, /fapi/ none of which work, at least for me.
If this is intended for some reason then please ignore but I figured I would bring it to your attention,

**Comment by RT-Tap** [comment]
404 responses for basically all REST requests in the POSTMAN collection, I tried for both the main exchange and the testnet.  In order to get it working I had to manually change the urls to .../api/v3/... for all of the of the REST requests in the collection and that's when I finally got a good 200 response.  

And yes that is the documentation I am using and used to verify that the POSTMAN collection seems to be wrong.  I also figured it might be correct and  I was doing something wrong on my end but wasn't sure so I brought it to your attention.

I'm now using the api with python and everything works well so far but I wanted to test it with postman first and that's when I ran into the issue.

Also this article is out of date (seems to use an old POSTMAN version) - https://academy.binance.com/en/articles/binance-api-series-pt-1-spot-trading-with-postman

**Comment by ishuen** [comment]
Please pull the latest code to your local environment. In the file you mentioned, there is no endpoint as `{{url}}/sapi/v1/ping`.. https://github.com/binance/binance-api-postman/blob/master/collections/binance_spot_api_v1.postman_collection.json
